# Generated by Django 3.2.12 on 2022-05-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img_one_table',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('img_id', models.CharField(max_length=150)),
                ('img_category', models.CharField(max_length=150)),
                ('img_label', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='imgdb')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webapp_img_one_table',
            },
        ),
    ]
