# Generated by Django 3.2.12 on 2022-05-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img_one_table',
            name='date',
        ),
        migrations.AddField(
            model_name='img_one_table',
            name='n_color',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='img_one_table',
            name='img_label',
            field=models.TextField(),
        ),
    ]
