# Generated by Django 3.2.12 on 2022-05-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20220506_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_one_table',
            name='image',
            field=models.ImageField(upload_to='1_Sharp_Egde/'),
        ),
    ]
