# Generated by Django 3.2.12 on 2022-05-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_img_one_table_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img_one_table',
            old_name='image',
            new_name='img_file',
        ),
    ]
