# Generated by Django 3.2.12 on 2022-05-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_image_img_one_table_img_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_info_table',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('img_id', models.CharField(max_length=150)),
                ('img_category', models.CharField(max_length=150)),
                ('n_color', models.IntegerField(default=1)),
            ],
        ),
    ]
