# Generated by Django 3.2.12 on 2022-05-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_img_info_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_processed_table',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('img_id', models.CharField(max_length=150)),
                ('img_category', models.CharField(max_length=150)),
                ('n_color', models.IntegerField(default=1)),
                ('img_file', models.ImageField(upload_to='1_Sharp_Egde/')),
                ('img_h', models.IntegerField(default=1920)),
                ('img_w', models.IntegerField(default=1080)),
                ('img_type', models.CharField(max_length=150)),
                ('isRGB', models.BooleanField()),
                ('img_label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webapp_img_processed_table',
            },
        ),
        migrations.RenameModel(
            old_name='img_one_table',
            new_name='add_img_table',
        ),
        migrations.RenameModel(
            old_name='img_info_table',
            new_name='img_helper_table',
        ),
        migrations.AlterModelTable(
            name='add_img_table',
            table='webapp_add_img_table',
        ),
        migrations.AlterModelTable(
            name='img_helper_table',
            table='webapp_img_helper_table',
        ),
    ]
