# Generated by Django 3.2.12 on 2022-05-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20220507_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_categories',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('img_categ', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'webapp_img_categories',
            },
        ),
    ]
