# Generated by Django 3.2.12 on 2022-05-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_img_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_img_table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='add_img_table',
            name='img_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.img_categories'),
        ),
        migrations.AlterField(
            model_name='img_categories',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='img_processed_table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='img_processed_table',
            name='img_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.img_categories'),
        ),
    ]
