# Generated by Django 3.2.12 on 2022-05-15 16:23

from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_add_img_table_img_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_img_table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.CharField(max_length=150)),
                ('n_color', models.IntegerField(default=1)),
                ('img_label', models.TextField(blank=True, null=True)),
                ('img_file', models.ImageField(upload_to=webapp.models.img_path)),
                ('img_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.img_categories')),
            ],
            options={
                'db_table': 'webapp_add_img_table2',
            },
        ),
    ]
