# Generated by Django 3.2.12 on 2022-05-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_add_img_table2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_img_table2',
        ),
    ]
