# Generated by Django 3.2.12 on 2022-05-15 16:34

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_delete_add_img_table2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_processed_table',
            name='img_file',
            field=models.ImageField(upload_to=webapp.models.img_path),
        ),
    ]
