# Generated by Django 3.2.12 on 2022-05-23 17:10

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_img_helper_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_processed_table',
            name='img_thumbs',
            field=models.ImageField(blank=True, null=True, upload_to=webapp.models.img_path),
        ),
    ]
