# Generated by Django 3.2.12 on 2022-05-24 02:36

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_img_processed_table_img_thumbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_img_table',
            name='img_thumbs',
            field=models.ImageField(blank=True, null=True, upload_to=webapp.models.img_path),
        ),
    ]
